

##################################################
# DK Sources
##################################################
DK_FP_GPIO_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../dk_hdl/fp_gpio/, \
clk_div_dk.v \
gpio_ctrl.v \
regN_ff.v \
))
