

##################################################
# DK Sources
##################################################
DK_TAG_ANC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../dk_hdl/tag_anc/, \
tag_rx.v \
tag_rx_ctrl.v \
))
