

##################################################
# DK Sources
##################################################
DK_MTX_ANC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../dk_hdl/main_anc/, \
mtx_sig.v \
mtx_single_tone.v \
mtx_ctrl.v \
usrp_tag_chip_mtx_sig.v \
usrp_tag_chip_mtx_ctrl.v \
))
