

##################################################
# DK Sources
##################################################
DK_MTX_ANC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../dk_hdl/main_anc/, \
mtx_sig.v \
mtx_ctrl.v \
mtx_sig2.v \
mtx_ctrl2.v \
hop_ctrl.v \
mtx_sig_tag_chip.v \
mtx_sig_tag_chip_nb.v \
mtx_ctrl_tag_chip.v \
mtx_ctrl_tag_chip_nb.v \
if_codes.mem \
))
