

##################################################
# DK Sources
##################################################
DK_MTX_ANC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../dk_hdl/main_anc/, \
mtx_sig.v \
))
