// -------------------------------------------------------------
// 
// File Name: hdlsrc\FFTHDLOptimizedExample_Burst\MINRESRX2_BUTTERFLY.v
// Created: 2022-07-02 22:54:14
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MINRESRX2_BUTTERFLY
// Source Path: FFTHDLOptimizedExample_Burst/FFT Burst/FFT/MINRESRX2_BUTTERFLY
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MINRESRX2_BUTTERFLY
          (clk,
           reset,
           btfIn1_re,
           btfIn1_im,
           btfIn2_re,
           btfIn2_im,
           btfIn_vld,
           twdl_re,
           twdl_im,
           btfOut1_re,
           btfOut1_im,
           btfOut2_re,
           btfOut2_im,
           btfOut_vld);


  input   clk;
  input   reset;
  input   signed [24:0] btfIn1_re;  // sfix25_En13
  input   signed [24:0] btfIn1_im;  // sfix25_En13
  input   signed [24:0] btfIn2_re;  // sfix25_En13
  input   signed [24:0] btfIn2_im;  // sfix25_En13
  input   btfIn_vld;
  input   signed [24:0] twdl_re;  // sfix25_En23
  input   signed [24:0] twdl_im;  // sfix25_En23
  output  signed [24:0] btfOut1_re;  // sfix25_En13
  output  signed [24:0] btfOut1_im;  // sfix25_En13
  output  signed [24:0] btfOut2_re;  // sfix25_En13
  output  signed [24:0] btfOut2_im;  // sfix25_En13
  output  btfOut_vld;


  reg signed [24:0] intdelay_reg [0:1];  // sfix25 [2]
  wire signed [24:0] intdelay_reg_next [0:1];  // sfix25_En13 [2]
  wire signed [24:0] din2Dly_re;  // sfix25_En13
  reg signed [24:0] intdelay_reg_1 [0:1];  // sfix25 [2]
  wire signed [24:0] intdelay_reg_next_1 [0:1];  // sfix25_En13 [2]
  wire signed [24:0] din2Dly_im;  // sfix25_En13
  wire signed [50:0] dinXTwdl_re;  // sfix51_En36
  wire signed [50:0] dinXTwdl_im;  // sfix51_En36
  wire dinXTwdl_vld;
  reg signed [24:0] intdelay_reg_2 [0:7];  // sfix25 [8]
  wire signed [24:0] intdelay_reg_next_2 [0:7];  // sfix25_En13 [8]
  wire signed [24:0] din1Dly_re;  // sfix25_En13
  reg signed [24:0] intdelay_reg_3 [0:7];  // sfix25 [8]
  wire signed [24:0] intdelay_reg_next_3 [0:7];  // sfix25_En13 [8]
  wire signed [24:0] din1Dly_im;  // sfix25_En13
  reg  [0:7] intdelay_reg_4;  // ufix1 [8]
  wire [0:7] intdelay_reg_next_4;  // ufix1 [8]
  wire din1Dly_vld;
  reg signed [51:0] minResRX2FFTButterfly_add1_re;  // sfix52
  reg signed [51:0] minResRX2FFTButterfly_add1_im;  // sfix52
  reg signed [51:0] minResRX2FFTButterfly_sub1_re;  // sfix52
  reg signed [51:0] minResRX2FFTButterfly_sub1_im;  // sfix52
  reg  minResRX2FFTButterfly_vld_reg;
  reg signed [51:0] minResRX2FFTButterfly_add1_cast_re;  // sfix52
  reg signed [51:0] minResRX2FFTButterfly_add1_cast_im;  // sfix52
  reg signed [51:0] minResRX2FFTButterfly_sub1_cast_re;  // sfix52
  reg signed [51:0] minResRX2FFTButterfly_sub1_cast_im;  // sfix52
  wire signed [51:0] minResRX2FFTButterfly_add1_re_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_add1_im_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub1_re_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub1_im_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_add1_cast_re_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_add1_cast_im_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub1_cast_re_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub1_cast_im_next;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_add_cast;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_add_cast_1;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_add_cast_2;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_add_cast_3;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub_cast;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub_cast_1;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub_cast_2;  // sfix52_En36
  wire signed [51:0] minResRX2FFTButterfly_sub_cast_3;  // sfix52_En36
  wire signed [51:0] btfOut1FP_re;  // sfix52_En36
  wire signed [51:0] btfOut1FP_im;  // sfix52_En36
  wire signed [51:0] btfOut2FP_re;  // sfix52_En36
  wire signed [51:0] btfOut2FP_im;  // sfix52_En36
  reg  btfOut_vld_1;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        intdelay_reg[0] <= 25'sb0000000000000000000000000;
        intdelay_reg[1] <= 25'sb0000000000000000000000000;
      end
      else begin
        intdelay_reg[0] <= intdelay_reg_next[0];
        intdelay_reg[1] <= intdelay_reg_next[1];
      end
    end

  assign din2Dly_re = intdelay_reg[1];
  assign intdelay_reg_next[0] = btfIn2_re;
  assign intdelay_reg_next[1] = intdelay_reg[0];



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        intdelay_reg_1[0] <= 25'sb0000000000000000000000000;
        intdelay_reg_1[1] <= 25'sb0000000000000000000000000;
      end
      else begin
        intdelay_reg_1[0] <= intdelay_reg_next_1[0];
        intdelay_reg_1[1] <= intdelay_reg_next_1[1];
      end
    end

  assign din2Dly_im = intdelay_reg_1[1];
  assign intdelay_reg_next_1[0] = btfIn2_im;
  assign intdelay_reg_next_1[1] = intdelay_reg_1[0];



  Complex4Multiply u_MUL4 (.clk(clk),
                           .reset(reset),
                           .btfIn2_re(din2Dly_re),  // sfix25_En13
                           .btfIn2_im(din2Dly_im),  // sfix25_En13
                           .din2Dly_vld(btfIn_vld),
                           .twdl_re(twdl_re),  // sfix25_En23
                           .twdl_im(twdl_im),  // sfix25_En23
                           .dinXTwdl_re(dinXTwdl_re),  // sfix51_En36
                           .dinXTwdl_im(dinXTwdl_im),  // sfix51_En36
                           .dinXTwdl_vld(dinXTwdl_vld)
                           );

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        intdelay_reg_2[0] <= 25'sb0000000000000000000000000;
        intdelay_reg_2[1] <= 25'sb0000000000000000000000000;
        intdelay_reg_2[2] <= 25'sb0000000000000000000000000;
        intdelay_reg_2[3] <= 25'sb0000000000000000000000000;
        intdelay_reg_2[4] <= 25'sb0000000000000000000000000;
        intdelay_reg_2[5] <= 25'sb0000000000000000000000000;
        intdelay_reg_2[6] <= 25'sb0000000000000000000000000;
        intdelay_reg_2[7] <= 25'sb0000000000000000000000000;
      end
      else begin
        intdelay_reg_2[0] <= intdelay_reg_next_2[0];
        intdelay_reg_2[1] <= intdelay_reg_next_2[1];
        intdelay_reg_2[2] <= intdelay_reg_next_2[2];
        intdelay_reg_2[3] <= intdelay_reg_next_2[3];
        intdelay_reg_2[4] <= intdelay_reg_next_2[4];
        intdelay_reg_2[5] <= intdelay_reg_next_2[5];
        intdelay_reg_2[6] <= intdelay_reg_next_2[6];
        intdelay_reg_2[7] <= intdelay_reg_next_2[7];
      end
    end

  assign din1Dly_re = intdelay_reg_2[7];
  assign intdelay_reg_next_2[0] = btfIn1_re;
  assign intdelay_reg_next_2[1] = intdelay_reg_2[0];
  assign intdelay_reg_next_2[2] = intdelay_reg_2[1];
  assign intdelay_reg_next_2[3] = intdelay_reg_2[2];
  assign intdelay_reg_next_2[4] = intdelay_reg_2[3];
  assign intdelay_reg_next_2[5] = intdelay_reg_2[4];
  assign intdelay_reg_next_2[6] = intdelay_reg_2[5];
  assign intdelay_reg_next_2[7] = intdelay_reg_2[6];



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        intdelay_reg_3[0] <= 25'sb0000000000000000000000000;
        intdelay_reg_3[1] <= 25'sb0000000000000000000000000;
        intdelay_reg_3[2] <= 25'sb0000000000000000000000000;
        intdelay_reg_3[3] <= 25'sb0000000000000000000000000;
        intdelay_reg_3[4] <= 25'sb0000000000000000000000000;
        intdelay_reg_3[5] <= 25'sb0000000000000000000000000;
        intdelay_reg_3[6] <= 25'sb0000000000000000000000000;
        intdelay_reg_3[7] <= 25'sb0000000000000000000000000;
      end
      else begin
        intdelay_reg_3[0] <= intdelay_reg_next_3[0];
        intdelay_reg_3[1] <= intdelay_reg_next_3[1];
        intdelay_reg_3[2] <= intdelay_reg_next_3[2];
        intdelay_reg_3[3] <= intdelay_reg_next_3[3];
        intdelay_reg_3[4] <= intdelay_reg_next_3[4];
        intdelay_reg_3[5] <= intdelay_reg_next_3[5];
        intdelay_reg_3[6] <= intdelay_reg_next_3[6];
        intdelay_reg_3[7] <= intdelay_reg_next_3[7];
      end
    end

  assign din1Dly_im = intdelay_reg_3[7];
  assign intdelay_reg_next_3[0] = btfIn1_im;
  assign intdelay_reg_next_3[1] = intdelay_reg_3[0];
  assign intdelay_reg_next_3[2] = intdelay_reg_3[1];
  assign intdelay_reg_next_3[3] = intdelay_reg_3[2];
  assign intdelay_reg_next_3[4] = intdelay_reg_3[3];
  assign intdelay_reg_next_3[5] = intdelay_reg_3[4];
  assign intdelay_reg_next_3[6] = intdelay_reg_3[5];
  assign intdelay_reg_next_3[7] = intdelay_reg_3[6];



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        intdelay_reg_4[0] <= 1'b0;
        intdelay_reg_4[1] <= 1'b0;
        intdelay_reg_4[2] <= 1'b0;
        intdelay_reg_4[3] <= 1'b0;
        intdelay_reg_4[4] <= 1'b0;
        intdelay_reg_4[5] <= 1'b0;
        intdelay_reg_4[6] <= 1'b0;
        intdelay_reg_4[7] <= 1'b0;
      end
      else begin
        intdelay_reg_4[0] <= intdelay_reg_next_4[0];
        intdelay_reg_4[1] <= intdelay_reg_next_4[1];
        intdelay_reg_4[2] <= intdelay_reg_next_4[2];
        intdelay_reg_4[3] <= intdelay_reg_next_4[3];
        intdelay_reg_4[4] <= intdelay_reg_next_4[4];
        intdelay_reg_4[5] <= intdelay_reg_next_4[5];
        intdelay_reg_4[6] <= intdelay_reg_next_4[6];
        intdelay_reg_4[7] <= intdelay_reg_next_4[7];
      end
    end

  assign din1Dly_vld = intdelay_reg_4[7];
  assign intdelay_reg_next_4[0] = btfIn_vld;
  assign intdelay_reg_next_4[1] = intdelay_reg_4[0];
  assign intdelay_reg_next_4[2] = intdelay_reg_4[1];
  assign intdelay_reg_next_4[3] = intdelay_reg_4[2];
  assign intdelay_reg_next_4[4] = intdelay_reg_4[3];
  assign intdelay_reg_next_4[5] = intdelay_reg_4[4];
  assign intdelay_reg_next_4[6] = intdelay_reg_4[5];
  assign intdelay_reg_next_4[7] = intdelay_reg_4[6];



  // minResRX2FFTButterfly
  always @(posedge clk or posedge reset)
    begin : minResRX2FFTButterfly_process
      if (reset == 1'b1) begin
        minResRX2FFTButterfly_add1_re <= 52'sh0000000000000;
        minResRX2FFTButterfly_add1_im <= 52'sh0000000000000;
        minResRX2FFTButterfly_sub1_re <= 52'sh0000000000000;
        minResRX2FFTButterfly_sub1_im <= 52'sh0000000000000;
        minResRX2FFTButterfly_add1_cast_re <= 52'sh0000000000000;
        minResRX2FFTButterfly_add1_cast_im <= 52'sh0000000000000;
        minResRX2FFTButterfly_sub1_cast_re <= 52'sh0000000000000;
        minResRX2FFTButterfly_sub1_cast_im <= 52'sh0000000000000;
        minResRX2FFTButterfly_vld_reg <= 1'b0;
        btfOut_vld_1 <= 1'b0;
      end
      else begin
        minResRX2FFTButterfly_add1_re <= minResRX2FFTButterfly_add1_re_next;
        minResRX2FFTButterfly_add1_im <= minResRX2FFTButterfly_add1_im_next;
        minResRX2FFTButterfly_sub1_re <= minResRX2FFTButterfly_sub1_re_next;
        minResRX2FFTButterfly_sub1_im <= minResRX2FFTButterfly_sub1_im_next;
        minResRX2FFTButterfly_add1_cast_re <= minResRX2FFTButterfly_add1_cast_re_next;
        minResRX2FFTButterfly_add1_cast_im <= minResRX2FFTButterfly_add1_cast_im_next;
        minResRX2FFTButterfly_sub1_cast_re <= minResRX2FFTButterfly_sub1_cast_re_next;
        minResRX2FFTButterfly_sub1_cast_im <= minResRX2FFTButterfly_sub1_cast_im_next;
        btfOut_vld_1 <= minResRX2FFTButterfly_vld_reg;
        minResRX2FFTButterfly_vld_reg <= din1Dly_vld;
      end
    end

  assign minResRX2FFTButterfly_add1_cast_re_next = minResRX2FFTButterfly_add1_re;
  assign minResRX2FFTButterfly_add1_cast_im_next = minResRX2FFTButterfly_add1_im;
  assign minResRX2FFTButterfly_sub1_cast_re_next = minResRX2FFTButterfly_sub1_re;
  assign minResRX2FFTButterfly_sub1_cast_im_next = minResRX2FFTButterfly_sub1_im;
  assign minResRX2FFTButterfly_add_cast = {{4{din1Dly_re[24]}}, {din1Dly_re, 23'b00000000000000000000000}};
  assign minResRX2FFTButterfly_add_cast_1 = {dinXTwdl_re[50], dinXTwdl_re};
  assign minResRX2FFTButterfly_add1_re_next = minResRX2FFTButterfly_add_cast + minResRX2FFTButterfly_add_cast_1;
  assign minResRX2FFTButterfly_add_cast_2 = {{4{din1Dly_im[24]}}, {din1Dly_im, 23'b00000000000000000000000}};
  assign minResRX2FFTButterfly_add_cast_3 = {dinXTwdl_im[50], dinXTwdl_im};
  assign minResRX2FFTButterfly_add1_im_next = minResRX2FFTButterfly_add_cast_2 + minResRX2FFTButterfly_add_cast_3;
  assign minResRX2FFTButterfly_sub_cast = {{4{din1Dly_re[24]}}, {din1Dly_re, 23'b00000000000000000000000}};
  assign minResRX2FFTButterfly_sub_cast_1 = {dinXTwdl_re[50], dinXTwdl_re};
  assign minResRX2FFTButterfly_sub1_re_next = minResRX2FFTButterfly_sub_cast - minResRX2FFTButterfly_sub_cast_1;
  assign minResRX2FFTButterfly_sub_cast_2 = {{4{din1Dly_im[24]}}, {din1Dly_im, 23'b00000000000000000000000}};
  assign minResRX2FFTButterfly_sub_cast_3 = {dinXTwdl_im[50], dinXTwdl_im};
  assign minResRX2FFTButterfly_sub1_im_next = minResRX2FFTButterfly_sub_cast_2 - minResRX2FFTButterfly_sub_cast_3;
  assign btfOut1FP_re = minResRX2FFTButterfly_add1_cast_re;
  assign btfOut1FP_im = minResRX2FFTButterfly_add1_cast_im;
  assign btfOut2FP_re = minResRX2FFTButterfly_sub1_cast_re;
  assign btfOut2FP_im = minResRX2FFTButterfly_sub1_cast_im;



  assign btfOut1_re = btfOut1FP_re[47:23];



  assign btfOut1_im = btfOut1FP_im[47:23];



  assign btfOut2_re = btfOut2FP_re[47:23];



  assign btfOut2_im = btfOut2FP_im[47:23];



  assign btfOut_vld = btfOut_vld_1;

endmodule  // MINRESRX2_BUTTERFLY

