

##################################################
# DK Sources
##################################################
DK_RX_ANC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../dk_hdl/rx_anc/, \
rx_anc.v \
rx_anc_ctrl.v \
))
