

##################################################
# DK Sources
##################################################
DK_KEY_SRCS = $(abspath $(addprefix $(BASE_DIR)/../../dk_hdl/usrp_key/, \
key_rx.v \
))
